Bartolo/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf.urls import handler404, handler500, handler403
from django.conf import settings
from django.contrib.sitemaps.views import sitemap
from django.views.generic.base import TemplateView
from django.views.decorators.cache import cache_page

import debug_toolbar

from Docencia.sitemaps import Dynamic

sitemaps = {
    "dynamic": Dynamic
}

urlpatterns = [
    # Admin
    path('jet/', include('jet.urls', 'jet')),
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    path('admin/', admin.site.urls),

    # Aplicacion
    path('docencia/', include('Docencia.urls')),
    path('sapereaude/', include('SapereAude.urls')),
    path('letranpay/', include('LetranPay.urls')),
    path('pagary/', include('Pagary.urls')),
    path('', include('Docencia.urls')),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
    
    # Social Auth
    path('social/', include('social_django.urls', namespace='social')),
    # Autentificacion
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path('pwdreset/', auth_views.PasswordResetView.as_view(), name='pwdreset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done',),
    path('password_reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm',),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete',),
    path('__debug__/', include(debug_toolbar.urls)),

    path('sitemap.xml', cache_page(60 * 60)(sitemap), {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('robots.txt', cache_page(60 * 60)(TemplateView.as_view(template_name="robots.txt", content_type="text/plain"))),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'Docencia.views.pag_404_not_found'
handler500 = 'Docencia.views.pag_500_error_server'
handler403 = 'Docencia.views.pag_403_permission_denied'

Docencia/urls.py
from django.urls import path
from . import views

__author__ = "Josue Isai Hernandez Sanchez"
__email__ = "josueisaihs@gmail.com"


urlpatterns = [
    path('', views.index.index, name='index'),
    path('api/suscribir', views.index.suscribeteAjax, name='api_index_suscribete'),
    path("eventos/", views.index.eventos, name="eventos"),
    path("evento/<int:pk>/", views.index.evento, name="evento"),
    path("cursos/", views.index.cursos, name="cursos"),
    path("curso/<slug:slug>/", views.index.curso, name="curso"),
    path("noticias/", views.index.noticias, name="noticias"),
    path("noticia/<slug:slug>/", views.index.noticia, name="noticia"),
    path("comunicado/<slug:slug>/", views.index.release, name="comunicado"),
    path("api/previewlink/", views.index.previewLink, name="api_index_previewlink"),
    path("recursos/", views.index.recursos, name="recursos"),
    path("politicaprivacidad/", views.politicaprivacidad, name="politicaprivacidad"),

    # Plataforma
    path("plataforma/foro/<slug:slug>", views.plataforma.messages, name="plataforma_messages"),
    path("plataforma/admin/foro/<slug:slug>", views.plataforma.adminmessages, name="plataforma_adminmessages"),
    path("plataforma/foro/send/", views.plataforma.send_message, name="plataforma_send_message"),
    path("plataforma/foro/delete/", views.plataforma.delete_message, name="plataforma_delete_message"),
    path("plataforma/foro/update/", views.plataforma.update_messages, name="plataforma_update_messages"),
    path("plataforma/foro/user/",views.plataforma.user_message, name="plataforma_user_message"),
    # Plataforma Estudiantes
    path("plataforma/dashboard/", views.plataforma.dashboard, name="plataforma_dashboard"),
    path("plataforma/dashboard/isreligious/", views.plataforma.isReligious, name="plataforma_is_religious"),
    path("plataforma/dashboard/<slug:tipo>/", views.plataforma.uploadphotocopy, name="plataforma_photocopia"),
    path("plataforma/dashboard/pay/communicate/<slug:slug>/", views.plataforma.communicatepay, name="plataforma_communicatepay"),
    path("plataforma/dashboard/pay/<slug:slug>/", views.plataforma.enrollmentpay, name="plataforma_enrollmentpay"),
    path("plataforma/dashboard/qr/<slug:slug>/", views.plataforma.genQR, name="plataforma_qrgen"),
    path("plataforma/dashboard/curso/<slug:slug>/", views.plataforma.curso, name="plataforma_curso"),
    path("plataforma/dashboard/curso/<slug:slug>/enrollment/", views.plataforma.enrollment, name="plataforma_enrollment"),
    path("api/plataforma/dashboard/enrollment/", views.plataforma.apienrollment, name="api_plataforma_enrollment"),
    path("api/plataforma/dashboard/homework/delete/", views.plataforma.apideletehomeworks, name="api_plataforma_delete_homework"),
    path("plataforma/dashboard/curso/<slug:slug>/homeworks/", views.plataforma.homeworks, name="plataforma_homeworks"),
    path("plataforma/dashboard/subject/<slug:slug>/", views.plataforma.subject, name="plataforma_subject"),
    path("plataforma/dashboard/clase/<slug:slug>", views.plataforma.clase, name="plataforma_clase"),
    path("plataforma/dashboard/clase/<slug:slug>/homework/", views.plataforma.homework, name="plataforma_homework"),
    path("plataforma/dashboard/recursos/<slug:slug>", views.plataforma.recursos, name="plataforma_recursos"),
    path("plataforma/dashboard/clase/recurso/<slug:slug>", views.plataforma.downloadResource, name="plataforma_recurso"),
    #Plataforma Profesores
    path("plataforma/admin/dashboard/", views.plataforma.admindashboard, name="plataforma_admin_index"),
    path("plataforma/admin/dashboard/pay/", views.plataforma.adminpay, name="plataforma_admin_pay"),
    path("plataforma/admin/dashboard/curso/<slug:slug>/", views.plataforma.admincourse, name="plataforma_admin_course"),
    path("plataforma/admin/dashboard/curso/recursos/<slug:slug>/", views.plataforma.adminrecursos, name="plataforma_admin_recursos"),
    path("plataforma/dashboard/clase/recurso/<slug:slug>/", views.plataforma.downloadAdminResource, name="plataforma_admin_recurso"),
    path("plataforma/dashboard/clase/recurso/<slug:slug>/<slug:slugclass>/delete/", views.plataforma.deleteAdminResource, name="plataforma_admin_del_recurso"),
    path("plataforma/admin/dashboard/curso/comunicado/crear/<slug:slug>/", views.plataforma.createcomunicate, name="plataforma_admin_comunicate"),
    path("plataforma/admin/dashboard/curso/grupo/crear/<slug:slug>/", views.plataforma.creategroup, name="plataforma_admin_crear_grupo"),
    path("plataforma/admin/dashboard/subject/<slug:slug>/", views.plataforma.adminsubject, name="plataforma_admin_subject"),
    path("plataforma/admin/dashboard/subject/<slug:slug>/homework/", views.plataforma.adminhomework, name="plataforma_admin_homework"),
    path("plataforma/admin/dashboard/subject/<slug:slug>/assistence/", views.plataforma.adminassistence, name="plataforma_admin_assistence"),
    path("plataforma/admin/dashboard/<slug:slug>/clase/crear/", views.plataforma.adminclass, name="plataforma_admin_clase"),
    path("plataforma/admin/dashboard/clase/delete/", views.plataforma.deleteclass, name="plataforma_admin_clase_delete"),
    path("plataforma/admin/dashboard/clase/editar/<slug:slug>/", views.plataforma.adminclass_edit, name="plataforma_admin_clase_editar"),
    path("plataforma/admin/dashboard/clase/file/upload/", views.plataforma.uploadfile, name="plataforma_admin_upload"),
    path("plataforma/admin/dashboard/clase/file/delete/", views.plataforma.deletefile, name="plataforma_admin_delete"),
    path("plataforma/admin/dashboard/comunicado/", views.plataforma.sendmasivemail, name="plataforma_admin_comunicado"),
    path("plataforma/admin/dashboard/clase/recurso/<slug:slug>/", views.plataforma.downloadTeacherResource, name="plataforma_admin_recurso"),
    path("api/plataforma/admin/dashboard/crear/grupo/", views.plataforma.apicreategroup, name="api_plataforma_admin_crear_grupo"),
    path("api/plataforma/admin/dashboard/assistence/", views.plataforma.apiassistence, name="api_plataforma_admin_assistence"),
    path("api/plataforma/admin/dashboard/homework/", views.plataforma.apiadminhomework, name="api_plataforma_admin_homework"),
    path("plataforma/admin/dashboard/grupo/<slug:grupo>", views.plataforma.admingroup, name="plataforma_admin_grupo"),
    path("plataforma/admin/dashboard/curso/<slug:slug>/studentslist/", views.plataforma.adminstudentslist, name="plataforma_admin_studentslist"),
    path("plataforma/admin/dashboard/curso/<slug:slug>/studentslist/<int:pk>/", views.plataforma.adminnotification, name="plataforma_admin_notification"),
    path("api/plataforma/admin/dashboard/curso/notification/", views.plataforma.sendnotificationmail, name="api_plataforma_admin_notification"),
    path("plataforma/admin/dashboard/subject/<slug:slug>/registro/", views.plataforma.registro, name="plataforma_admin_registro"),
    path("api/plataforma/admin/dashboard/subject/registro/", views.plataforma.apiregistro, name="api_plataforma_admin_registro"),

    path('admision/dashboard/', views.datospersonales.dashboard, name='admision_dashboard'),
    path('admision/registro/', views.datospersonales.registro, name='admision_registro'),
    path('admision/success/', views.datospersonales.registrocompletado, name='admision_registro_ok'),
    path('admision/seleccioncurso/', views.admision.selectcourse, name='admision_seleccion_curso'),
    path('admision/seleccioncurso/<int:coursePk>/application/', views.admision.application, name='admision_applicacion'),
    path('api/admision/application/add/', views.admision.applicationAjax, name='api_admision_aplicacion'),
    path('api/admision/application/cancel/', views.admision.applicationCancelAjax, name='api_admision_aplicacion_cancel'),

    path('admision/admin/dashboard/', views.admon.admindashboard, name='admision_admin'),
    path('admision/admin/dashboard/<int:coursepk>/', views.admon.admindashboard_course, name='admision_admin_course'),
    path('api/admision/admin/dashboard/denegar/', views.admon.admindashboard_denegar, name='api_admision_denegar'),
    path('api/admision/admin/dashboard/accion/', views.admon.admindashboard_accion, name='api_admision_accion'),
    path('api/admision/admin/dashboard/comment/', views.admon.updateComment, name='api_admision_comment'),
    path('admision/admin/dashboard/detail/<int:coursepk>/', views.admon.admindashboard_detail, name='admision_admin_detail'),
    path('admision/admin/dashboard/detail/student/<int:apppk>/', views.admon.admindashboard_student_detail, name='admision_admin_student_detail'),
]

Pagary/urls.py
from django.urls import path
from . import views

__author__ = "Josue Isai Hernandez Sanchez"
__email__ = "josueisaihs@gmail.com"


urlpatterns = [
    path("", views.pagary, name="pagary")
]

Blog/models.py
import os

from django.db import models
from django_ckeditor_5.fields import CKEditor5Field
from django.contrib import admin
from django.utils.text import slugify
from django.utils.translation import gettext as _
from django.utils.timezone import now
from django.contrib.auth.models import User, Group

class Author(models.Model):
    """Model definition for Author."""
    slug = models.SlugField(max_length=250, default="")
    user = models.OneToOneField(User, on_delete=models.CASCADE, default=1, limit_choices_to={'groups': 'Blog Autor'})
    name = models.CharField(_("Nombre"), max_length=50)
    lastname = models.CharField(_("Apellido"), max_length=50)
    grade = models.CharField('Grado Científico', max_length=20,
        choices=(("Ing.", "Ingeniero"), ("Arq.", "Arquitecto"), ("Lic.", "Licenciado"), ("Ms.C.", "Master en Ciencias"),
                ("Dr.C.", "Doctor en Ciencias"), ("PhD.C.", "Postdoctor en Ciencias"), ("", "Ninguno")), default=""
    )
    
    ocupation = models.CharField(_("Ocupacion"), max_length=150)
    resume = models.TextField(_("Resumé"))
    photo = models.ImageField(_("Foto"), upload_to=os.path.join('static', 'blog', 'author'))

    class Meta:
        """Meta definition for Author."""
        unique_together = [("name", "lastname")]
        verbose_name = 'Autor'
        verbose_name_plural = 'Autores'

    def getFullname(self):
        return "%s %s" % (self.name, self.lastname)

    def __str__(self):
        """Unicode representation of Author."""
        return self.getFullname()

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = self._get_unique_slug()
        super().save(*args, **kwargs)

    def _get_unique_slug(self):
        slug = slugify(self.getFullname())
        unique_slug = slug
        num = 1
        while Author.objects.filter(slug=unique_slug).exists():
            unique_slug = '{}-{}'.format(slug, num)
            num += 1
        return unique_slug
    
@admin.register(Author)
class AuthorAdmin(admin.ModelAdmin):
    '''Admin View for Author'''
    list_display = ('user', 'name', 'lastname', 'grade')
    readonly_fields = ('slug',)
    search_fields = ('name', 'lastname')
    ordering = ('lastname', 'name')

class Blog(models.Model):
    """Model definition for Blog."""
    slug = models.SlugField(max_length=250, default="")
    name = models.CharField(_("Nombre"), max_length=150, unique=True)
    description = CKEditor5Field('Descripción', config_name='extends')
    authors = models.ManyToManyField("Blog.Author", verbose_name=_("Autor(es)"))
    image = models.ImageField(_("Imagen"), upload_to=os.path.join('static', 'blog', 'blog'))
    active =  models.BooleanField(_("Activo"), default=False)

    class Meta:
        """Meta definition for Blog."""
        verbose_name = 'Blog'
        verbose_name_plural = 'Blogs'

    def __str__(self):
        """Unicode representation of Blog."""
        return "%s" % self.name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = self._get_unique_slug()
        super().save(*args, **kwargs)

    def _get_unique_slug(self):
        slug = slugify(self.name)
        unique_slug = slug
        num = 1
        while Author.objects.filter(slug=unique_slug).exists():
            unique_slug = '{}-{}'.format(slug, num)
            num += 1
        return unique_slug

@admin.register(Blog)
class BlogAdmin(admin.ModelAdmin):
    '''Admin View for Blog'''
    list_display = ('name', 'active')
    readonly_fields = ('slug',)
    search_fields = ('name', 'name__authors__name', 'name__authors__lastname')
    ordering = ('name',)

class Article(models.Model):
    slug = models.SlugField('Slug', max_length=250)
    blog = models.ForeignKey("Blog.Blog", verbose_name='Blog', on_delete=models.CASCADE)
    authors = models.ManyToManyField("Blog.Author", verbose_name="Autor(es)")
    title = models.CharField('Título', max_length=250)
    subtitle = models.CharField('Subtítulo', max_length=250, default="", blank=True)
    abstract = models.TextField("Resumen")
    image = models.ImageField('Imagen', upload_to='static/blog/%Y/%m/%d/%H/%M/')
    body = CKEditor5Field('Cuerpo', config_name='extends', default="<p>Sin texto</p>")
    datepub = models.DateField('Publicación', auto_now=True)
    dateupdate = models.DateField('Última Actualización', auto_now=True)

    topost = models.BooleanField(_("Publicar"), default=False)
    allow = models.BooleanField(_("Permitir"), default=False)

    class Meta:
        """Meta definition for MODELNAME."""
        unique_together = [('blog', 'title')]
        verbose_name = 'Artículo'
        verbose_name_plural = 'Artículos'

    def __str__(self):
        """Unicode representation of MODELNAME."""
        return '%s' % self.title

    def _get_unique_slug(self):
        slug = slugify(self.title)
        unique_slug = slug
        num = 1
        while Article.objects.filter(slug=unique_slug).exists():
            unique_slug = '{}-{}'.format(slug, num)
            num += 1
        return unique_slug
 
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = self._get_unique_slug()
        self.dateupdate = now()
        super().save(*args, **kwargs)

@admin.register(Article)
class ArticleAdmin(admin.ModelAdmin):
    list_display = ('title', 'subtitle', 'blog', 'datepub', 'dateupdate')
    list_filter = ('blog', 'authors__ocupation', 'allow', 'topost')
    readonly_fields = ('slug',)
    search_fields = ('title', 'subtitle', 'abstract', 'authors__name', 'authors__lastname', 
    'author__grade', 'blog__name', )
    ordering = ('-datepub', '-dateupdate', 'title')
    date_hierarchy = 'datepub'

Docencia/Index/forms.py
from django import forms

from Docencia.Index.models import Recurso

class RecursoForm(forms.ModelForm):    
    class Meta:
        model = Recurso
        fields = ("name", "recurso", "tipo", "courses")

templates/docencia/plataforma/adminclass.html
{% extends './admindashboard.html' %}
{% load static %}

{% block header %}
    <h5>
        <a href="{% url 'plataforma_admin_subject' subject.slug %}" class="">
            <i class="fas fa-arrow-left"></i></a> {{ subject.course.name }} / {{ subject.name}}
    </h5>
{% endblock header %}
    
{% block dashboard_content %}    
    {% if edit %}
        <div class="alert alert-success" role="alert">
            <h4 class="alert-heading">¡Atención!</h4>
            <p>Habilitada la funcionalidad de edición de las clases. Sentimos las molestias que esto pudo ocacionar</p>
            <hr>
            <small class="mb-0">Equipo Técnico Centro · Fray Bartolomé de las Casas</small>
        </div>
    {% endif %}
        
    <form class="my-3" action="." method="POST" id="id_classform">
        {% csrf_token %}

        {% if form.errors %}
            {% for field in form %}
                {% for error in field.errors %}
                    <div class="alert alert-danger">
                        <strong>{{ error|escape }}</strong>
                    </div>
                {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endif %}
        
        <div class="row mb-3 g-3">
            <div class="col-md-6">
                <div class="input-group">
                    <span class="input-group-text">Título</span>
                    {{ form.name }}
                </div>
            </div>

            <div class="col-md-6">
                <div class="input-group date" id="id_datepub_div" data-target-input="nearest">
                    {{ form.datepub }}
                    <button class="btn btn-outline-secondary" type="button" data-target="#id_datepub_div" data-toggle="datetimepicker"><i class="fa fa-calendar"></i></button>
                </div>
            </div>
        </div>

        <div class="ckeditor mb-3">
            <label class="required" for="id_classbody"></label>
            {{ form.classbody }}
        </div>

        <div class="border rounded py-4 px-2">
            <div enctype="multipart/form-data" id="id_uploadfile_form">
                <p><i class="fas fa-paperclip"></i> Archivos Adjuntos <span class="badge rounded-pill bg-primary badge-files invisible"></span> <span class="files-size text-secondary invisible float-rigth"></span></p>
                <div class="input-group">
                    <div class="form-file">
                        <input type="file" class="form-file-input" id="inputGroupFile01" aria-describedby="inputGroupFileAddon01">
                        <label class="form-file-label" for="inputGroupFile01">
                            <span class="form-file-text file-name">Archivo...</span>
                            <span class="form-file-button">Buscar</span>
                        </label>
                    </div>                
                </div>
                <div class="d-flex align-items-center form-upload invisible">
                    <strong class="text"></strong>
                    <div class="spinner-border ml-auto" role="status" aria-hidden="true"></div>
                </div>
            </div>
            
            <div id="id_toastError" class="toast fixed-bottom my-5 mx-2" data-delay="10000" data-animation="true" role="alert" aria-live="assertive" aria-atomic="true">
                <div class="toast-header bg-danger text-white">
                    <strong class="mr-auto"><i class="fa fa-exclamation-circle fa-lg mr-2"></i> Error</strong>
                    <small class="">Ahora</small>
                    <button type="button" class="ml-2 mb-1 close text-white" data-dismiss="toast" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="toast-body toast-error-text">
                    Ha ocurrido un error
                </div>
            </div>

            <div class="files-upload">
                <div class="d-flex align-items-stretch mt-2">
                    
                    {% for resource in class_edit.resources.all %}
                        <a class="d-inline-flex border px-2 rounded m-1" role="button" onclick="$(this).remove();removeFile('{{ resource.name }}', {{ resource.recurso.size }});">
                            <div class="d-flex flex-column text-center text-small py-1">
                                <div class="text-primary">
                                    <i class="fa                                     
                                    {% with resource as recurso %}                                        
                                        {% if recurso.tipo == 'html' or recurso.tipo == 'css' or recurso.tipo == 'js' or recurso.tipo == 'python' %} 
                                            fa-file-code
                                            {% endif %}                
                                            {% if recurso.tipo == 'audio' %}
                                            fa-file-audio
                                            {% endif %}                
                                            {% if recurso.tipo == 'video' %}
                                            fa-file-video
                                            {% endif %}
                                            {% if recurso.tipo == 'imagen' %}
                                            fa-file-image
                                            {% endif %}                
                                            {% if recurso.tipo == 'documento' or recurso.tipo == 'conferencia' or recurso.tipo == 'programa' or recurso.tipo == 'reglamento' %}
                                            fa-file-alt 
                                        {% endif %}
                                    {% endwith %}"></i> {{ resource.name }}
                                </div>
                            </div>
                            <div class="ml-2 flex-fill align-self-center text-small">
                                {{ resource.recurso.size|filesizeformat }}
                            </div>
                            <div class="ml-2 flex-fill align-self-center text-small">
                                <i class="fas fa-times"></i>
                            </div>
                        </a>
                    {% endfor %}
                        
                </div>
            </div>
        </div>
        
        {{ form.subject }}
        {{ form.recursosjson }}
        
        <input type="submit" id="id_salvar" class="btn btn-primary mt-3" value="Salvar" >
        {% if edit %}
            <button type="button" class="btn btn-danger mt-3" onclick="removeClass('{{ class_edit.slug }}')">Eliminar</button>            
        {% endif %}
            
    </form>
{% endblock %}

{% block importScripts %}
<link href="{% static 'django_ckeditor_5/dist/styles.css' %}" type="text/css" media="all" rel="stylesheet">
<script defer src="{% static 'django_ckeditor_5/dist/bundle.js' %}"></script>
<!-- Calendario -->
<script defer src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.23.0/moment.min.js" integrity="sha256-VBLiveTKyUZMEzJd6z2mhfxIqz3ZATCuVMawPZGzIfA=" crossorigin="anonymous"></script>

<!-- Tempus Dominus Bootstrap 4 -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/css/tempusdominus-bootstrap-4.min.css" integrity="sha256-XPTBwC3SBoWHSmKasAk01c08M6sIA5gF5+sRxqak2Qs=" crossorigin="anonymous" />
<script defer src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/js/tempusdominus-bootstrap-4.min.js" integrity="sha256-z0oKYg6xiLq3yJGsp/LsY9XykbweQlHl42jHv2XTBz4=" crossorigin="anonymous"></script>
<script defer src="{% static 'letran/js/datetimepicker.js' %}"></script>

<script defer src="{% static 'letran/js/ajaxupload.js' %}"></script>
{% endblock importScripts %}


{% block scripts %}
    const urlindex = "{% url 'plataforma_admin_index' %}";
    const urlupload = "{% url 'plataforma_admin_upload' %}";
    const urldelete = "{% url 'plataforma_admin_delete' %}";
    const urldeleteclass = "{% url 'plataforma_admin_clase_delete' %}";
    const urlsubject = "{% url 'plataforma_admin_subject' subject.slug %}"
    const subject = {{ subject.pk }};
    let recursos = {name: []}
    let filess = 0;
    {% if class_edit %}
        const filesm = {{ class_edit.resources.all|length }}
        
        {% for resource in class_edit.resources.all %}
            filess += {{ resource.recurso.size }};
            recursos.name.push("{{ resource.name }}");
        {% endfor %}
            
    {% else %} 
        const filesm = 0;       
    {% endif %}

    let filesUpload = filesm;
    let filesSize = filess;
{% endblock scripts %}
    
    

templates/docencia/plataforma/homework.html
{% extends './dashboard.html' %}
{% load static %}

{% block header %}
    <h5>
        <a href="{% url 'plataforma_clase' clase.slug %}" class="link-light">
            <i class="fas fa-arrow-left"></i>
        </a> {{ clase.subject.course.name }} / {{ clase.subject.name }} / {{ clase.name }} / Enviar Tarea
    </h5>
{% endblock header %}
    
{% block dashboard_content %}
    <div class="row m-2 g-2">
        <form action="." method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% if form.errors %}                
                {% for key, error in form.errors.items %}
                    {% if key == '__all__' %}
                        <div class="alert alert-danger" role="alert">
                            {{ error | escape }}
                        </div>
                    {% endif %}
                {% endfor %}                    
            {% endif %}

            <div class="mb-3">
                <label for="id_name" class="form-label">Nombre</label>
                {% if form.name.errors %}                
                    {% for error in form.name.errors %}
                        <div class="alert alert-danger" role="alert">
                            {{ error|escape }}
                        </div>
                    {% endfor %}                    
                {% endif %}
                {{ form.name }}
            </div>

            <div class="mb-3">
                <label for="id_file" class="form-label">Busca el archivo</label>
                {% if form.file.errors %}                
                    {% for error in form.file.errors %}
                        <div class="alert alert-danger" role="alert">
                            {{ error|escape }}
                        </div>
                    {% endfor %}                    
                {% endif %}
                {{ form.file }}
                <div id="emailHelp" class="form-text">{{ form.file.help_text }}</div>
            </div>
            
            {% if form.clase.errors %}                
                {% for error in form.clase.errors %}
                    <div class="alert alert-danger" role="alert">
                        {{ error|escape }}
                    </div>
                {% endfor %}                    
            {% endif %}
            {{ form.clase }}

            {% if form.student.errors %}                
                {% for error in form.student.errors %}
                    <div class="alert alert-danger" role="alert">
                        {{ error|escape }}
                    </div>
                {% endfor %}                    
            {% endif %}
            {{ form.student }}

            {% if form.edition.errors %}                
                {% for error in form.edition.errors %}
                    <div class="alert alert-danger" role="alert">
                        {{ error|escape }}
                    </div>
                {% endfor %}                    
            {% endif %}
            {{ form.edition }}
            <br>
            <input type="submit" class="btn btn-primary"value="Enviar">
        </form>        
    </div>
{% endblock dashboard_content %}
{% block scripts %}
    var clase = document.querySelector('#id_clase')
    clase.value = {{ clase.pk }}
    var student = document.querySelector('#id_student')
    student.value = {{ student.pk }}
    var edition = document.querySelector('#id_edition')
    edition.value = {{ edition.pk }}
{% endblock scripts %}